baseURL = "https://siddharam.com.tw/"
languageCode = "en-us"
title = "Siddharam"
SEOTitle = "Siddharam | 寫程式的文字人 | 西打藍"
subhead = "寫程式的文字人"
description = "文字紀錄可能性 | 程式創造可能性"
theme = "hugo-theme-cleanwhite"
hasCJKLanguage = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "文字紀錄可能性 | 程式創造可能性"
  title = "Siddharam | 寫程式的文字人 | 西打藍"
  SEOTitle = "Siddharam | 寫程式的文字人 | 西打藍"
  keyword = "Siddharam, 西打藍, 工程師日常, 技術筆記, Hugo, 記者日常"
  navbarTitle = "寫程式的文字人"
  slogan = "寫程式的文字人"
  about_me = "關於"
  image_404 = ""
  title_404 = "請待會再嘗試一次 :("

  sidebar_about_description = "文字紀錄可能性 | 程式創造可能性"


[params.social]
  email          = ""
  github         = ""


  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


